SRC += muse.c

MOUSEKEY_ENABLE   = yes
COMMAND_ENABLE    = no
CONSOLE_ENABLE    = no
MIDI_ENABLE       = yes
TAP_DANCE_ENABLE  = yes
AUTO_SHIFT_ENABLE = yes
FAUXCLICKY_ENABLE = yes
AUDIO_ENABLE      = yes
